[package]
name = "libpg_query_rust"
version = "0.1.0"
authors = ["Sebastian <19Sebastian95@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# build = "build.rs"

[dependencies]
jni = "0.18.0"

[lib]
crate_type = ["cdylib"]